Bids cpac dev
flywheel-apps/c-pac pull request #4
Opened 2019-08-13 21:57 UTC by joshicola

Added some package/module structure from work with Andy.

Tested in "dry-run" mode (without executing the c-pac command line).

2019-08-14 19:47 UTC, joshicola commented
Default pipeline settings provide a 4 GB zipped payload.

This payload size is dependent on these settings. 

Working directory for c-pac is in /tmp/ and /scratch/.  These are not saved to the payload.

2019-08-14 20:26 UTC, AndysWorth approved these changes

2019-08-21 21:45 UTC, lmperry commented on Dockerfile
>  MAINTAINER Michael Perry <michaelperry@flywheel.io>
Please modify to Flywheel <support@flywheel.io>

2019-08-21 21:46 UTC, lmperry commented on manifest.json
>      "custom": {
Please add  the following to the ```custom``` key. 
```json
"flywheel": {"suite": "BIDS Apps"}
```

That will help keep these gears sorted in the UI.

2019-08-21 21:49 UTC, lmperry commented on run.py
>              context.destination['id']='5d2761383289d60037e8b180'
Can we remove these test blocks and instead use a custom config.json file?

2019-08-21 21:50 UTC, lmperry requested changes
Looks good. A couple of minor changes requested.

2019-08-27 18:09 UTC, AndysWorth approved these changes

2019-08-27 20:13 UTC, merged